language: python
sudo: false
python: 2.7

# 3.7 needs xenial and sudo https://github.com/travis-ci/travis-ci/issues/9815
# This enables 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 2.7
      env:
        - TOXENV=py27
    - python: 3.4
      env:
        - TOXENV=py34
    - python: 3.5
      env:
        - TOXENV=py35
    - python: 3.6
      env:
        - TOXENV=py36
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - TOXENV=py37
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - TOXENV=lint

install:
  - pip install tox

script:
  - tox -e $TOXENV

after_success:
  - pip install codecov
  - codecov
